name: one_time_pad
description: An implementation of the one-time pad system.
version: 1.0.1
repository: https://github.com/ernestoittig/one_time_pad

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.0

dev_dependencies:
  effective_dart: ^1.3.2
  test: ^1.17.12

executables:
  one_time_pad:
  otp: one_time_pad
